name = "Robust Iniwa Custom"
license = "MIT"
licenselink = "https://github.com/iniwa/hugo_theme_robust-iniwa/blob/master/LICENSE.md"
description = "A customized Robust theme ."
homepage = "https://github.com/iniwa/hugo-theme-robust-iniwa"
tags = ["blog", "responsive", "custom"]
features = ["sticky-sidebar", "toc", "accordion"]
min_version = '0.60.0'

[author]
  name = "iniwa"
  homepage = "https://iniwach.com"

[original]
  author = "Daisuke Tsuji"
  homepage = "http://yet.unresolved.xyz"
  repo = "https://github.com/dim0627/hugo_theme_robust"
